# Generated by Django 2.2 on 2019-04-16 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Colonie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nombre_de_cadres', models.CharField(max_length=2)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('remarque', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Rucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRuche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeuilleVisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('colonie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruches.Colonie')),
                ('rucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruches.Rucher')),
                ('typeRuche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruches.TypeRuche')),
            ],
        ),
        migrations.AddField(
            model_name='colonie',
            name='rucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruches.Rucher'),
        ),
        migrations.AddField(
            model_name='colonie',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruches.TypeRuche'),
        ),
    ]
