# Generated by Django 2.2 on 2019-04-16 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0002_auto_20190416_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonie',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
