# Generated by Django 2.2 on 2019-04-16 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0004_auto_20190416_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonie',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
