# Generated by Django 2.2 on 2019-04-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0007_auto_20190416_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='rucher',
            name='addresseP',
            field=models.CharField(default='', max_length=200),
        ),
    ]
