# Generated by Django 2.2 on 2019-04-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0008_rucher_addressep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rucher',
            old_name='addresseP',
            new_name='adresseP',
        ),
    ]
