# Generated by Django 2.2 on 2019-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0009_auto_20190416_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='rucher',
            name='adresseS',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rucher',
            name='codePostal',
            field=models.CharField(default='', max_length=6),
        ),
    ]
