# Generated by Django 2.2 on 2019-04-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0010_auto_20190416_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='rucher',
            name='ville',
            field=models.CharField(default='', max_length=200),
        ),
    ]
