# Generated by Django 2.2 on 2019-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruches', '0011_rucher_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonie',
            name='remarque',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
